1722078721.414509 2024-07-27 19:12:01 MainProcess-1156719 MainThread-140353952024384 parsl.dataflow.dflow:98 __init__ INFO: Starting DataFlowKernel with config
Config(
    app_cache=True, 
    checkpoint_files=None, 
    checkpoint_mode=None, 
    checkpoint_period=None, 
    dependency_resolver=None, 
    executors=(ThreadPoolExecutor(
        label='threads', 
        max_threads=2, 
        storage_access=None, 
        thread_name_prefix='', 
        working_dir=None
    ),), 
    exit_mode='cleanup', 
    garbage_collect=True, 
    initialize_logging=True, 
    internal_tasks_max_threads=10, 
    max_idletime=120.0, 
    monitoring=None, 
    retries=0, 
    retry_handler=None, 
    run_dir='runinfo', 
    std_autopath=None, 
    strategy='simple', 
    strategy_period=5, 
    usage_tracking=0
)
1722078721.414677 2024-07-27 19:12:01 MainProcess-1156719 MainThread-140353952024384 parsl.dataflow.dflow:100 __init__ INFO: Parsl version: 2024.07.22
1722078721.414778 2024-07-27 19:12:01 MainProcess-1156719 MainThread-140353952024384 parsl.usage_tracking.usage:118 __init__ DEBUG: Tracking level: 0
1722078721.414867 2024-07-27 19:12:01 MainProcess-1156719 MainThread-140353952024384 parsl.dataflow.dflow:128 __init__ INFO: Run id is: b602bf48-0eb7-46a5-96ce-e9cd8e7be0f6
1722078721.482818 2024-07-27 19:12:01 MainProcess-1156719 MainThread-140353952024384 parsl.dataflow.dflow:135 __init__ DEBUG: Considering candidate for workflow name: /home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/dataflow/dflow.py
1722078721.482889 2024-07-27 19:12:01 MainProcess-1156719 MainThread-140353952024384 parsl.dataflow.dflow:135 __init__ DEBUG: Considering candidate for workflow name: /home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/dataflow/dflow.py
1722078721.482941 2024-07-27 19:12:01 MainProcess-1156719 MainThread-140353952024384 parsl.dataflow.dflow:135 __init__ DEBUG: Considering candidate for workflow name: /home/ubuntu/data/test/parsl_pro/parsl_script.py
1722078721.482988 2024-07-27 19:12:01 MainProcess-1156719 MainThread-140353952024384 parsl.dataflow.dflow:141 __init__ DEBUG: Using parsl_script.py as workflow name
1722078721.483115 2024-07-27 19:12:01 MainProcess-1156719 MainThread-140353952024384 parsl.dataflow.memoization:163 __init__ INFO: App caching initialized
1722078721.483182 2024-07-27 19:12:01 MainProcess-1156719 MainThread-140353952024384 parsl.jobs.strategy:145 __init__ DEBUG: Scaling strategy: simple
1722078721.486119 2024-07-27 19:12:01 MainProcess-1156719 MainThread-140353952024384 parsl.dataflow.dflow:1016 submit DEBUG: Task 0 will be sent to executor threads
1722078721.486217 2024-07-27 19:12:01 MainProcess-1156719 MainThread-140353952024384 parsl.dataflow.dflow:818 _add_output_deps DEBUG: Adding output dependencies
1722078721.486278 2024-07-27 19:12:01 MainProcess-1156719 MainThread-140353952024384 parsl.dataflow.dflow:1067 submit DEBUG: Added output dependencies
1722078721.486326 2024-07-27 19:12:01 MainProcess-1156719 MainThread-140353952024384 parsl.dataflow.dflow:1080 submit DEBUG: Gathering dependencies
1722078721.486371 2024-07-27 19:12:01 MainProcess-1156719 MainThread-140353952024384 parsl.dataflow.dflow:1083 submit DEBUG: Gathered dependencies
1722078721.486415 2024-07-27 19:12:01 MainProcess-1156719 MainThread-140353952024384 parsl.dataflow.dflow:1098 submit INFO: Task 0 submitted for App install_flexflow, not waiting on any dependency
1722078721.486474 2024-07-27 19:12:01 MainProcess-1156719 MainThread-140353952024384 parsl.dataflow.dflow:1104 submit DEBUG: Task 0 set to pending state with AppFuture: <AppFuture at 0x7fa6afe8d700 state=pending>
1722078721.486886 2024-07-27 19:12:01 MainProcess-1156719 Dependency-Launch_0-140353880971008 parsl.dataflow.memoization:222 check_memo DEBUG: Task 0 will not be memoized
1722078721.487040 2024-07-27 19:12:01 MainProcess-1156719 MainThread-140353952024384 parsl.dataflow.dflow:1016 submit DEBUG: Task 1 will be sent to executor threads
1722078721.487376 2024-07-27 19:12:01 MainProcess-1156719 MainThread-140353952024384 parsl.dataflow.dflow:818 _add_output_deps DEBUG: Adding output dependencies
1722078721.489061 2024-07-27 19:12:01 MainProcess-1156719 MainThread-140353952024384 parsl.dataflow.dflow:1067 submit DEBUG: Added output dependencies
1722078721.489154 2024-07-27 19:12:01 MainProcess-1156719 MainThread-140353952024384 parsl.dataflow.dflow:1080 submit DEBUG: Gathering dependencies
1722078721.489269 2024-07-27 19:12:01 MainProcess-1156719 MainThread-140353952024384 parsl.dataflow.dflow:1083 submit DEBUG: Gathered dependencies
1722078721.489382 2024-07-27 19:12:01 MainProcess-1156719 Dependency-Launch_0-140353880971008 parsl.dataflow.dflow:776 launch_task INFO: Parsl task 0 try 0 launched on executor threads
1722078721.489457 2024-07-27 19:12:01 MainProcess-1156719 MainThread-140353952024384 parsl.dataflow.dflow:1098 submit INFO: Task 1 submitted for App train_model, not waiting on any dependency
1722078721.489593 2024-07-27 19:12:01 MainProcess-1156719 Dependency-Launch_0-140353880971008 parsl.dataflow.dflow:1476 log_std_stream INFO: Standard out for task 0 will not be redirected.
1722078721.489691 2024-07-27 19:12:01 MainProcess-1156719 MainThread-140353952024384 parsl.dataflow.dflow:1104 submit DEBUG: Task 1 set to pending state with AppFuture: <AppFuture at 0x7fa6afe2c490 state=pending>
1722078721.489794 2024-07-27 19:12:01 MainProcess-1156719 Dependency-Launch_0-140353880971008 parsl.dataflow.dflow:1476 log_std_stream INFO: Standard error for task 0 will not be redirected.
1722078721.490220 2024-07-27 19:12:01 MainProcess-1156719 Dependency-Launch_0-140353880971008 parsl.process_loggers:27 wrapped DEBUG: Normal ending for _launch_if_ready_async on thread Dependency-Launch_0
1722078721.490520 2024-07-27 19:12:01 MainProcess-1156719 Dependency-Launch_0-140353880971008 parsl.dataflow.memoization:222 check_memo DEBUG: Task 1 will not be memoized
1722078721.491645 2024-07-27 19:12:01 MainProcess-1156719 Dependency-Launch_0-140353880971008 parsl.dataflow.dflow:776 launch_task INFO: Parsl task 1 try 0 launched on executor threads
1722078721.491914 2024-07-27 19:12:01 MainProcess-1156719 Dependency-Launch_0-140353880971008 parsl.dataflow.dflow:1478 log_std_stream INFO: Standard out for task 1 will be redirected to train_model.out
1722078721.492278 2024-07-27 19:12:01 MainProcess-1156719 Dependency-Launch_0-140353880971008 parsl.dataflow.dflow:1478 log_std_stream INFO: Standard error for task 1 will be redirected to train_model.err
1722078721.492464 2024-07-27 19:12:01 MainProcess-1156719 Dependency-Launch_0-140353880971008 parsl.process_loggers:27 wrapped DEBUG: Normal ending for _launch_if_ready_async on thread Dependency-Launch_0
1722078721.495414 2024-07-27 19:12:01 MainProcess-1156719 MainThread-140353952024384 parsl.dataflow.dflow:1016 submit DEBUG: Task 2 will be sent to executor _parsl_internal
1722078721.495533 2024-07-27 19:12:01 MainProcess-1156719 MainThread-140353952024384 parsl.dataflow.dflow:818 _add_output_deps DEBUG: Adding output dependencies
1722078721.495602 2024-07-27 19:12:01 MainProcess-1156719 MainThread-140353952024384 parsl.dataflow.dflow:1067 submit DEBUG: Added output dependencies
1722078721.495660 2024-07-27 19:12:01 MainProcess-1156719 MainThread-140353952024384 parsl.dataflow.dflow:1080 submit DEBUG: Gathering dependencies
1722078721.495778 2024-07-27 19:12:01 MainProcess-1156719 MainThread-140353952024384 parsl.dataflow.dflow:1083 submit DEBUG: Gathered dependencies
1722078721.495842 2024-07-27 19:12:01 MainProcess-1156719 MainThread-140353952024384 parsl.dataflow.dflow:1098 submit INFO: Task 2 submitted for App deferred_getattr, waiting on task 1
1722078721.495913 2024-07-27 19:12:01 MainProcess-1156719 MainThread-140353952024384 parsl.dataflow.dflow:1104 submit DEBUG: Task 2 set to pending state with AppFuture: <AppFuture at 0x7fa6afe2c190 state=pending>
1722078721.496105 2024-07-27 19:12:01 MainProcess-1156719 Dependency-Launch_0-140353880971008 parsl.dataflow.dflow:664 _launch_if_ready_async DEBUG: Task 2 has outstanding dependencies, so launch_if_ready skipping
1722078721.496328 2024-07-27 19:12:01 MainProcess-1156719 Dependency-Launch_0-140353880971008 parsl.process_loggers:27 wrapped DEBUG: Normal ending for _launch_if_ready_async on thread Dependency-Launch_0
1722078722.313579 2024-07-27 19:12:02 MainProcess-1156719 ThreadPoolExecutor-0_1-140353864185600 parsl.app.errors:113 reraise DEBUG: Reraising exception of type <class 'parsl.app.errors.BashExitFailure'>
1722078722.314119 2024-07-27 19:12:02 MainProcess-1156719 ThreadPoolExecutor-0_1-140353864185600 parsl.dataflow.dflow:351 handle_exec_update INFO: Task 1 try 0 failed with exception of type BashExitFailure
1722078722.314355 2024-07-27 19:12:02 MainProcess-1156719 ThreadPoolExecutor-0_1-140353864185600 parsl.dataflow.dflow:397 handle_exec_update ERROR: Task 1 failed after 0 retry attempts
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/dataflow/dflow.py", line 348, in handle_exec_update
    res = self._unwrap_remote_exception_wrapper(future)
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/dataflow/dflow.py", line 618, in _unwrap_remote_exception_wrapper
    result.reraise()
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/app/errors.py", line 117, in reraise
    raise v
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/app/errors.py", line 141, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/app/bash.py", line 94, in remote_side_bash_executor
    raise pe.BashExitFailure(func_name, proc.returncode)
parsl.app.errors.BashExitFailure: bash_app train_model failed with unix exit code 134
1722078722.315619 2024-07-27 19:12:02 MainProcess-1156719 ThreadPoolExecutor-0_1-140353864185600 concurrent.futures:332 _invoke_callbacks ERROR: exception calling callback for <AppFuture at 0x7fa6afe2c490 state=finished raised BashExitFailure>
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/dataflow/dflow.py", line 348, in handle_exec_update
    res = self._unwrap_remote_exception_wrapper(future)
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/dataflow/dflow.py", line 618, in _unwrap_remote_exception_wrapper
    result.reraise()
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/app/errors.py", line 117, in reraise
    raise v
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/app/errors.py", line 141, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/app/bash.py", line 94, in remote_side_bash_executor
    raise pe.BashExitFailure(func_name, proc.returncode)
parsl.app.errors.BashExitFailure: bash_app train_model failed with unix exit code 134

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/concurrent/futures/_base.py", line 330, in _invoke_callbacks
    callback(self)
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/dataflow/dflow.py", line 1123, in callback_adapter
    self.launch_if_ready(task_record)
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/dataflow/dflow.py", line 646, in launch_if_ready
    self.dependency_launch_pool.submit(self._launch_if_ready_async, task_record)
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/concurrent/futures/thread.py", line 167, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
1722078722.316685 2024-07-27 19:12:02 MainProcess-1156719 ThreadPoolExecutor-0_1-140353864185600 parsl.dataflow.dflow:1478 log_std_stream INFO: Standard out for task 1 will be redirected to train_model.out
1722078722.316819 2024-07-27 19:12:02 MainProcess-1156719 ThreadPoolExecutor-0_1-140353864185600 parsl.dataflow.dflow:1478 log_std_stream INFO: Standard error for task 1 will be redirected to train_model.err
1722078726.483866 2024-07-27 19:12:06 MainProcess-1156719 JobStatusPoller-Timer-Thread-140353889820976-140353889363712 parsl.jobs.strategy:184 _general_strategy DEBUG: general strategy starting with strategy_type simple for 0 executors
1722078726.484181 2024-07-27 19:12:06 MainProcess-1156719 JobStatusPoller-Timer-Thread-140353889820976-140353889363712 parsl.process_loggers:27 wrapped DEBUG: Normal ending for _general_strategy on thread JobStatusPoller-Timer-Thread-140353889820976
1722078731.485534 2024-07-27 19:12:11 MainProcess-1156719 JobStatusPoller-Timer-Thread-140353889820976-140353889363712 parsl.jobs.strategy:184 _general_strategy DEBUG: general strategy starting with strategy_type simple for 0 executors
1722078731.485749 2024-07-27 19:12:11 MainProcess-1156719 JobStatusPoller-Timer-Thread-140353889820976-140353889363712 parsl.process_loggers:27 wrapped DEBUG: Normal ending for _general_strategy on thread JobStatusPoller-Timer-Thread-140353889820976
1722078734.497835 2024-07-27 19:12:14 MainProcess-1156719 ThreadPoolExecutor-0_0-140353872578304 parsl.dataflow.dflow:597 _complete_task INFO: Task 0 completed (launched -> exec_done)
1722078734.498113 2024-07-27 19:12:14 MainProcess-1156719 ThreadPoolExecutor-0_0-140353872578304 parsl.dataflow.dflow:1476 log_std_stream INFO: Standard out for task 0 will not be redirected.
1722078734.498231 2024-07-27 19:12:14 MainProcess-1156719 ThreadPoolExecutor-0_0-140353872578304 parsl.dataflow.dflow:1476 log_std_stream INFO: Standard error for task 0 will not be redirected.
1722078734.498536 2024-07-27 19:12:14 MainProcess-1156719 MainThread-140353952024384 parsl.dataflow.dflow:1206 atexit_cleanup WARNING: Python is exiting with a DFK still running. You should call parsl.dfk().cleanup() before exiting to release any resources
